const exportedFunctions = [
  "_jsalloc_unsafe",
  "_jsalloc_zero",
  "_free",

  "_roaring_bitmap_create_js",
  "_roaring_bitmap_create_with_capacity",
  "_roaring_bitmap_free",
  "_roaring_bitmap_is_empty",
  "_roaring_bitmap_add",
  "_roaring_bitmap_remove",
  "_roaring_bitmap_maximum",
  "_roaring_bitmap_minimum",
  "_roaring_bitmap_is_subset",
  "_roaring_bitmap_is_strict_subset",
  "_roaring_bitmap_to_uint32_array",
  "_roaring_bitmap_equals",
  "_roaring_bitmap_optimize_js",
  "_roaring_bitmap_select_js",
  "_roaring_bitmap_get_index_js",
  "_roaring_bitmap_at_js",
  "_roaring_bitmap_and_cardinality",
  "_roaring_bitmap_or_cardinality",
  "_roaring_bitmap_andnot_cardinality",
  "_roaring_bitmap_xor_cardinality",
  "_roaring_bitmap_rank",
  "_roaring_bitmap_and_inplace",
  "_roaring_bitmap_or_inplace",
  "_roaring_bitmap_xor_inplace",
  "_roaring_bitmap_andnot_inplace",
  "_roaring_bitmap_intersect",
  "_roaring_bitmap_jaccard_index_js",
  "_roaring_bitmap_has_js",

  "_roaring_bitmap_add_checked",
  "_roaring_bitmap_remove_checked",

  "_roaring_bitmap_portable_size_in_bytes",
  "_roaring_bitmap_portable_serialize",
  "_roaring_bitmap_portable_deserialize_safe",

  "_roaring_bitmap_size_in_bytes",
  "_roaring_bitmap_serialize",
  "_roaring_bitmap_deserialize_safe",

  "_roaring_bitmap_get_cardinality_js",
  "_roaring_bitmap_flip_range_static_js",
  "_roaring_bitmap_from_range_js",
  "_roaring_bitmap_contains_range_js",
  "_roaring_bitmap_add_range_js",
  "_roaring_bitmap_remove_range_js",
  "_roaring_bitmap_flip_range_inplace_js",
  "_roaring_bitmap_range_cardinality_js",
  "_roaring_bitmap_add_offset_js",
  "_roaring_bitmap_copy",
  "_roaring_bitmap_overwrite",
  "_roaring_bitmap_run_optimize",
  "_roaring_bitmap_shrink_to_fit_js",
  "_roaring_bitmap_remove_run_compression",
  "_roaring_bitmap_and_js",
  "_roaring_bitmap_or_js",
  "_roaring_bitmap_xor_js",
  "_roaring_bitmap_andnot_js",
  "_roaring_bitmap_or_many",
  "_roaring_bitmap_xor_many",
  "_roaring_bitmap_intersect_with_range_js",

  "_roaring_iterator_js_new",
  "_roaring_iterator_js_next",
  "_roaring_iterator_js_clone",
  "_roaring_iterator_js_gte",

  "_roaring_sync_iter_init",
  "_roaring_sync_iter_next",
  "_roaring_sync_iter_min",

  "_roaring_sync_bulk_add_init",
  "_roaring_sync_bulk_add_chunk",

  "_roaring_bitmap_remove_many",
  "_roaring_sync_bulk_remove_init",
  "_roaring_sync_bulk_remove_chunk",
];

module.exports = exportedFunctions;
